server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  ai:
    deepseek:
      api-key: ${DEEPSEEK_AGENT_DEV_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-flash
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/agent_dev?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

